name: build dist

on:
  push:
  pull_request:
permissions:
  contents: write

jobs:
  linux-build:
    name: build on linux
    runs-on: ubuntu-20.04
    steps:
    - name: checkout
      uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: apt update
      run: |
        sudo apt-get update
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: temurin
    - name: cache AVD
      uses: actions/cache@v3
      env:
        cache-name: cache-avd
      with:
        path: /home/runner/.android/gradle/avd
        key: ${{ runner.os }}-gradle-avd
    - name: cache gradle caches
      uses: actions/cache@v3
      env:
        cache-name: cache-gradle-caches
      with:
        path: /home/runner/.gradle/caches/
        key: ${{ runner.os }}-gradle-caches
    - name: Bump version
      uses: chkfung/android-version-actions@v1.2.1
      with:
        gradlePath: app/build.gradle.kts
        versionCode: ${{github.run_number}}
    - name: build
      run: ./gradlew build bundle
    - name: Sign app APK
      uses: r0adkll/sign-android-release@v1
      id: sign_app
      with:
        releaseDirectory: app/build/outputs/bundle/stableRelease
        signingKeyBase64: ${{ secrets.SIGNING_KEY_BASE64 }}
        alias: ${{ secrets.SIGNING_KEY_ALIAS }}
        keyStorePassword: ${{ secrets.SIGNING_KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.SIGNING_KEY_PASSWORD }}
    - name: upload artifact
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: apks and aabs
        path: |
          app/build/outputs/apk/*/debug/*.apk
          ${{steps.sign_app.outputs.signedReleaseFile}}
    - name: Create Release
      uses: ncipollo/release-action@v1.12.0
      if: startsWith(github.ref, 'refs/tags/')
      with:
        artifacts: app/build/outputs/apk/*/debug/*.apk,${{steps.sign_app.outputs.signedReleaseFile}}
